name: 🐛 버그 리포트
description: 프론트엔드 버그 신고
title: "[bug] "
labels: ["bug", "frontend"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 버그 리포트
        발견된 버그를 신고해주세요 🍓

  - type: textarea
    id: bug_description
    attributes:
      label: 버그 설명
      placeholder: 어떤 버그인지 자세히 설명해주세요
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: 재현 방법
      placeholder: |
        1. '...' 페이지로 이동
        2. '...' 버튼 클릭
        3. '...' 입력
        4. 에러 발생
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: 예상 동작
      placeholder: 어떻게 동작해야 하는지 설명해주세요
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: 실제 동작
      placeholder: 실제로 어떻게 동작하는지 설명해주세요
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 환경 정보
      value: |
        - OS: 
        - 브라우저: 
        - 브라우저 버전: 
        - 디바이스: (PC/Mobile)
        - 화면 해상도: 
    validations:
      required: true

  - type: textarea
    id: console_errors
    attributes:
      label: 콘솔 에러 (선택사항)
      placeholder: 브라우저 개발자 도구의 에러 메시지를 첨부해주세요